### ISSUE TITLE
Possible to use require in as needed basics 

### ISSUE THREAD

**Issue by taboca** [Stuk/require1k#10]
I wonder if you have a means for me to load JS as needed — say I click a button, then I want to have the XHR and so..

**Comment by Stuk** [comment]
Yes, you can use the `R` function in an onclick handler to dynamically load a javascript module

**Comment by taboca** [comment]
From the docs, is the impression I had, indeed. However, when looking in the browser development tool, it seemed to me that the the script was priorly loaded, therefore even when I had moved it to the inside of the R function. 

I will retest again and let you know.

**Comment by taboca** [comment]
Ok, my back for not paying attention on the different samples, from your docs. The real approach, for delayed (or as needed) load is the second example. 

I end up testing and creating a sample: 

https://github.com/taboca/sample-require1k-delayed

And confirm as working, as I have used the following example

'''
R("./index", function (err, index) {
    if (err) {
        console.error(err.statusText);
        return;
    }
    // use the exports object as needed
});
'''

**Comment by taboca** [comment]
Something I have noticed, however, that was confusing me, is that the initial loaded infrastructure indeed loaded the require('something') that was stated as a comment: 

```
  //remote = require('../js/remote/push');
```

Notice that I moved from such approach, to the global R approach, but as I left the above as comment, yet I kept seeing the "../js/remote/push" being loaded. :)

**Comment by Stuk** [comment]
Glad to hear you got it fixed!

Re: loading requires in comments, yep, that's a limitation of the require "parser". It only looks for text that matches a require call, and doesn't understand comments.

**Comment by taboca** [comment]
Totally fine considering also your 1k limitation and how it's parsing dependent too.
