### ISSUE TITLE
Loading via <script> with a module inside

### ISSUE THREAD

**Issue by lukasoppermann** [Stuk/require1k#14]
Hey @Stuk,

I am having the following problem:

I have a file that is loaded via a normal script tag (not a module) but it has a require statement inside. How can I get this working with require1k?

**Comment by Stuk** [comment]
The best way to load it would be with the `data-main` attribute.

Instead of:

```html
<script src="file.js"></script>
```

use:

```html
<script src="require1k.min.js" data-main="./file"></script>
```

**Comment by lukasoppermann** [comment]
Ohh, this somehow did not work for me. I figured this would only work if file.js is a commonjs module as well? I will investigate this again.

**Comment by lukasoppermann** [comment]
Okay, I had something wrong. Don't ask me what, but now it is working fine. Thanks.
