### ISSUE TITLE
error on loading index.js from node_modules

### ISSUE THREAD

**Issue by dyenereks** [Stuk/require1k#15]
Hi @Stuk 

I'm having some issue on loading node modules:

for example if I require:
```javascript
require('apollo-client');
```
it produces error:

![screen shot 2017-12-07 at 9 41 19 am](https://user-images.githubusercontent.com/33676841/33694417-ee1fec40-db32-11e7-9866-a7247269ab07.png)

It seems that the index.js isn't loaded automatically(?). Is there a way to fix my issue?

**Comment by Stuk** [comment]
This is mentioned under [Limitations](https://github.com/Stuk/require1k/blob/master/README.md#limitations). You'll have to add the path to the index file after `apollo-client`
