### ISSUE TITLE
FR: make loader configurable

### ISSUE THREAD

**Issue by ray007** [Stuk/require1k#18]
It would be very nice if the actual loading of data from network was encapsulated in a function, so it could be replace by i.e. [basket.js](https://github.com/addyosmani/basket.js).

**Comment by Stuk** [comment]
Thanks for the issue. Unfortunately to hit the self-imposed 1k size the code is not designed to allow this kind of configurability. If you're looking for that it would be best to find a project designed to actually run in production :)

**Comment by ray007** [comment]
Hmm, didn't think this would blow up the code size by more than maybe a few bytes. Pity.
