### ISSUE TITLE
Load files from bower

### ISSUE THREAD

**Issue by lukasoppermann** [Stuk/require1k#6]
Hey, can I load deps from bower?

In requirejs you have a config object, that lest you say something like this.

```javascript
require.config({
    baseUrl: "./",
    paths: {
        "jquery": "../bower_components/jquery/dist/jquery"
    }
});
```

Can I somehow do this with require1k?

**Comment by Stuk** [comment]
There is no way to do this with require1k. I have an idea that may or may not work with the size restrictions.

As a work around you can explicitly `require('./bower_components/jquery/dist/jquery')`

**Comment by Stuk** [comment]
The idea I had won't work, so afraid the explicit require is the only way.
